#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir//bin/sh" ]; then
  exec "$basedir//bin/sh"  "$basedir/node_modules/vtop/bin/vtop.js" "$@"
else 
  exec /bin/sh  "$basedir/node_modules/vtop/bin/vtop.js" "$@"
fi
